name: ARCHE-Filechecker and Virusscan

on:
  workflow_dispatch

jobs:
  check_files:
    name: Run the ARCHE-Filechecker
    runs-on: ubuntu-latest
    env:
      ARCHE_USER: $ARCHE_USER
      ARCHE_PASSWORD: ${{secrets.ARCHE_PASSWORD}}
      ARCHE: https://arche-dev.acdh-dev.oeaw.ac.at/api
      TOPCOLID: https://id.acdh.oeaw.ac.at/grocerist
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: install python things
      run: pip install -r requirements.txt
    - name: create arche metadata
      run: python arche/make_arche_rdf.py
    - name: check files
      run: ./arche/arche__filechecker.sh
    - uses: actions/upload-artifact@v4
      with:
        name: filechecker-report
        path: fc_out
    - name: Run virus scan
      run: ./arche/arche__viruscheck.sh
    
