
name: Make TEIs

on:
  schedule:
  - cron: "50 23 * * *"
  workflow_dispatch:

jobs:
  download:
    name: make teis
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
      - name: docx to tei
        run: |
          python scripts/download_docx.py
      - name: split and enrich files
        run: |
          python scripts/create_doc_teis.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: TEI updates
